<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GraveOps.Core\GraveOps.Core.csproj" />
    <ProjectReference Include="..\..\src\GraveOps.Platform.Windows\GraveOps.Platform.Windows.csproj" />
    <ProjectReference Include="..\..\src\GraveOps.Desktop.Windows\GraveOps.Desktop.Windows.csproj" />
  </ItemGroup>
</Project>
